'use client';

import RevenueChart from "@/components/insights/RevenueChart";
import { useInsightsData } from "@/hooks/useInsightsData";
import { Info } from "lucide-react";

export default function InsightsPage() {
  const { dailyData, isLoading } = useInsightsData();

  if (isLoading) {
    return (
      <div className="flex h-full items-center justify-center">
        <div className="text-gray-500">Loading insights...</div>
      </div>
    );
  }

  return (
    <div className="space-y-8">
      <div>
        <h1 className="text-3xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-cyan-400 to-purple-500 neon-text">Insights</h1>
        <p className="mt-1 text-sm text-gray-400">
          Deep dive into your campaign performance and attribution.
        </p>
      </div>

      <RevenueChart data={dailyData} />

      <div className="rounded-xl glass-card p-6 border border-blue-500/20 shadow-[0_0_15px_rgba(59,130,246,0.1)]">
        <div className="flex">
          <div className="flex-shrink-0">
            <Info className="h-5 w-5 text-cyan-400 drop-shadow-[0_0_8px_rgba(34,211,238,0.8)]" aria-hidden="true" />
          </div>
          <div className="ml-3">
            <h3 className="text-sm font-bold text-cyan-300">Attribution Logic Applied</h3>
            <div className="mt-2 text-sm text-gray-300 leading-relaxed">
              <p>
                When visualizing data, we apply the following logic: If a video was posted on a specific date, 
                all revenue generated by that influencer from that date until the date of their next video 
                is attributed to the first video.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
